import { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import { Shield, Lock, Key, EyeOff, Sparkles } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Privacy Policy | AETHERIA — PGSharp Key Vault',
  description: 'How customer transactional data, email, and payment references are cryptographically protected.',
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-black text-white relative overflow-hidden selection:bg-cyan-500/30">
      {/* Background Subtle Radial Aura */}
      <div
        className="absolute inset-0 pointer-events-none opacity-30"
        style={{
          background:
            'radial-gradient(ellipse 70% 50% at 50% 10%, rgba(6, 182, 212, 0.15) 0%, rgba(16, 185, 129, 0.05) 50%, transparent 80%)',
        }}
      />

      {/* Floating Cyber Header */}
      <nav className="fixed top-0 left-0 right-0 z-40 bg-black/60 backdrop-blur-xl border-b border-cyan-500/10">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 h-16 sm:h-20 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3 group">
            <div className="w-8 h-8 sm:w-10 sm:h-10 flex items-center justify-center transition-transform group-hover:scale-110">
              <Image
                src="/logo.png"
                alt="AETHERIA"
                width={36}
                height={36}
                className="w-full h-full object-contain"
              />
            </div>
            <div className="flex flex-col">
              <span className="text-white font-sans font-bold text-sm sm:text-base tracking-[0.2em] uppercase">
                AETHERIA
              </span>
              <span className="text-[9px] font-mono text-cyan-400 font-semibold tracking-widest uppercase">
                PGSharp Key Vault
              </span>
            </div>
          </Link>
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 px-3.5 sm:px-4 py-1.5 rounded-full bg-neutral-900/80 border border-neutral-700 hover:border-cyan-400/60 text-xs font-mono text-neutral-300 hover:text-cyan-300 transition-all shadow-sm"
          >
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            <span>Return to Vault</span>
          </Link>
        </div>
      </nav>

      {/* Main Content Container */}
      <div className="pt-28 sm:pt-36 pb-20 px-4 max-w-4xl mx-auto relative z-10">
        <div className="bg-neutral-950/80 border border-cyan-500/20 backdrop-blur-2xl rounded-3xl p-6 sm:p-12 shadow-[0_0_50px_rgba(0,0,0,0.8)]">
          <div className="flex items-center gap-4 mb-8">
            <div className="w-12 h-12 sm:w-14 sm:h-14 rounded-2xl bg-cyan-950/50 border border-cyan-500/40 flex items-center justify-center text-cyan-400 shadow-[0_0_20px_rgba(6,182,212,0.3)]">
              <Shield size={26} />
            </div>
            <div>
              <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-cyan-950/60 border border-cyan-500/30 text-cyan-300 text-[10px] font-mono tracking-widest uppercase mb-1">
                <Lock size={11} className="text-cyan-400" />
                Data Protection
              </div>
              <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">Privacy Policy</h1>
              <p className="text-neutral-400 text-xs font-mono mt-1">Last Updated: September 2026 • Version 1.8.8</p>
            </div>
          </div>

          <div className="space-y-6 text-neutral-300 text-sm leading-relaxed border-t border-neutral-800/80 pt-6">
            <section className="bg-neutral-900/40 border border-neutral-800/60 rounded-2xl p-5">
              <h2 className="text-base font-bold text-cyan-300 mb-2 flex items-center gap-2">
                <Key size={16} />
                1. Transactional Data We Collect
              </h2>
              <p className="text-neutral-400 text-xs sm:text-sm leading-relaxed">
                We strictly collect only minimal, non-sensitive transactional data required to fulfill and deliver your digital product purchase:
              </p>
              <ul className="list-disc list-inside space-y-1.5 text-neutral-400 text-xs sm:text-sm mt-3 ml-1">
                <li><strong className="text-neutral-200">Email Address:</strong> Used solely to dispatch your PGSharp license key, order invoice, and activation guide.</li>
                <li><strong className="text-neutral-200">Transaction Reference ID:</strong> Cryptographic reference number generated by payment networks (UPI UTR / PayPal Transaction ID) for automated key verification.</li>
              </ul>
            </section>

            <section className="bg-neutral-900/40 border border-neutral-800/60 rounded-2xl p-5">
              <h2 className="text-base font-bold text-cyan-300 mb-2 flex items-center gap-2">
                <EyeOff size={16} />
                2. Payment Security & Zero Financial Storage
              </h2>
              <p className="text-neutral-400 text-xs sm:text-sm leading-relaxed">
                All checkout transactions are processed directly through certified payment rails and official banking networks (Direct UPI and PayPal). AETHERIA <strong className="text-neutral-200">never stores, logs, intercepts, or has access to</strong> your credit/debit card numbers, UPI PINs, CVVs, bank account credentials, or passwords.
              </p>
            </section>

            <section className="bg-neutral-900/40 border border-neutral-800/60 rounded-2xl p-5">
              <h2 className="text-base font-bold text-cyan-300 mb-2 flex items-center gap-2">
                <Lock size={16} />
                3. AES-256 Key Encryption & Zero Marketing Spam
              </h2>
              <p className="text-neutral-400 text-xs sm:text-sm leading-relaxed">
                All digital license keys are encrypted at rest using industry-standard AES-256 authenticated encryption. Customer emails are never sold, rented, shared with third-party advertisers, or used for promotional spam.
              </p>
            </section>

            <section className="bg-neutral-900/40 border border-neutral-800/60 rounded-2xl p-5">
              <h2 className="text-base font-bold text-cyan-300 mb-2 flex items-center gap-2">
                <Sparkles size={16} />
                4. Session Storage & Cookies
              </h2>
              <p className="text-neutral-400 text-xs sm:text-sm leading-relaxed">
                We only utilize essential local storage to preserve your order verification state during payment redirects and anonymous web analytics to ensure fast load times and server uptime.
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
}
