import { Metadata } from 'next';
import Link from 'next/link';
import { Shield } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Privacy Policy | AETHERIA',
  description: 'How customer transactional data, email, and payment references are protected.',
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-hero-gradient text-white">
      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-40 glass border-b border-surface-700/50">
        <div className="max-w-5xl mx-auto px-4 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5 hover:opacity-80 transition-opacity">
            <span className="text-2xl">🎮</span>
            <span className="text-white font-extrabold text-lg">PGSharp Keys</span>
          </Link>
          <Link
            href="/#plans"
            className="text-xs font-semibold text-brand-400 hover:text-brand-300 transition-colors"
          >
            ← Back to Storefront
          </Link>
        </div>
      </nav>

      <div className="pt-28 pb-20 px-4 max-w-4xl mx-auto">
        <div className="bg-surface-800 border border-surface-600 rounded-3xl p-8 sm:p-12 shadow-card">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-12 h-12 rounded-2xl bg-brand-900/60 border border-brand-700/50 flex items-center justify-center text-brand-400">
              <Shield size={24} />
            </div>
            <div>
              <h1 className="text-3xl font-black text-white">Privacy Policy</h1>
              <p className="text-gray-400 text-xs mt-1">Last Updated: August 2026</p>
            </div>
          </div>

          <div className="space-y-6 text-gray-300 text-sm leading-relaxed border-t border-surface-700 pt-6">
            <section>
              <h2 className="text-lg font-bold text-white mb-2">1. Data We Collect</h2>
              <p>
                We only collect minimal transactional data required to deliver and verify your digital product purchase:
              </p>
              <ul className="list-disc list-inside space-y-1 text-gray-400 mt-2 ml-2">
                <li><strong>Email Address:</strong> To deliver the license key, activation guide, and purchase receipt.</li>
                <li><strong>Transaction ID:</strong> Cryptographic reference ID generated by payment gateways (Razorpay / PayPal).</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-2">2. Payment Security & Zero Card Storage</h2>
              <p>
                All payments are processed securely through certified Level-1 PCI-DSS compliant payment gateways (Razorpay and PayPal). We <strong>never store, log, or have access to</strong> your credit card numbers, UPI PINs, CVVs, or banking credentials.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-2">3. Key Encryption & Data Retention</h2>
              <p>
                All digital license keys are securely encrypted at rest using authenticated vault encryption in our database. Your data is never sold, shared with advertisers, or used for unsolicited marketing.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-white mb-2">4. Cookies & Local Storage</h2>
              <p>
                We only use essential local session storage to temporarily preserve your order reference during the checkout payment redirect.
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
}
